### PR TITLE
Patch order

### PR DESCRIPTION
**Pull request by xuanwan05**
Changing shipping options will update the total amount, which will only be calculated on the server side. When patching an order, the amount value from the retrieved order will be used as the base amount for the patch order call, in order to update the total amount.

Screenshot 2023-02-22 at 12 50 00 PM
Screenshot 2023-02-22 at 12 50 24 PM
Screenshot 2023-02-22 at 12 51 12 PM
Screenshot 2023-02-22 at 12 51 25 PM

### CODE REVIEW

File: src/order/patch-order.ts [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+  name: string;
+  message: string;
+  debug_id: string;
+};
+
+interface HttpErrorResponse extends Error {
+  statusCode?: number;
+}
+
+export default async function onShippingChange(
```
Comment (gregjopa) [inline src/order/patch-order.ts:21]:
```suggestion
export async function onShippingChange(
```

File: public/buttons.html [hunk 2]
```diff
@@ -114,6 +114,19 @@ <h1>PayPal Buttons Example</h1>
                 errorObject: error,
               });
             },
+            onShippingChange(data) {
+              console.log(data);
```
Comment (dtjones404) [inline public/buttons.html:118]: Do we want to keep this console log here?  Not sure if it's just left over from debugging.

File: src/controller/order-controller.ts [hunk 3]
```diff
@@ -127,3 +162,70 @@ export async function captureOrderController(fastify: FastifyInstance) {
     },
   });
 }
+
+// Patch order
+export type ShippingOption = {
+  id: string;
+  label: string;
+  type: string;
```
Comment (dtjones404) [inline src/controller/order-controller.ts:170]: I wonder if it's worth using a literal union for `type` here, maybe something like:

 `type: "SHIPPING" | "PICKUP" | (whatever the other options are)`
 
 Seems like a good practice to teach, and might make it slightly more clear to readers what this field is meant to represent.

Comment (gregjopa) [reply src/controller/order-controller.ts:170]: Good suggestion @dtjones404! We may be able to leverage paypal-js for this type.

Comment (gregjopa) [reply src/controller/order-controller.ts:170]: Would this type work? https://github.com/paypal/paypal-js/blob/9e3472a26d28f971fbe2d90bad7b57c969f4a8b5/types/apis/shipping.d.ts#L10

Comment (dtjones404) [reply src/controller/order-controller.ts:170]: Looks great!

File: public/buttons.html (hunk 2 above)
Comment (gregjopa) [inline public/buttons.html:118]:
```suggestion
```

File: src/controller/order-controller.ts [hunk 4]
```diff
@@ -127,3 +162,70 @@ export async function captureOrderController(fastify: FastifyInstance) {
...
+  const { access_token: accessToken } = await getAuthToken();
+
+  let shippingPayload = {
+    selectedShippingOption,
+    orderID,
+  };
+
+  const data = await onShippingChange(accessToken, shippingPayload);
+  // Send a response with a 204 status code and no body
+  reply.code(204).send();
```
Comment (gregjopa) [inline src/controller/order-controller.ts:192]: Does the `patch` call always return a 204? Or is there a chance it returns a 200? Wondering if we need to check the `data` variable above to see if there's a response or not.

```js
if (data) {
  reply.send(data);
} else {
  reply.code(204).send();
}
```

File: src/order/retrieve-order.ts [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+  message: string;
+  debug_id: string;
+};
+
+type HttpErrorResponse = {
+  statusCode?: number;
+  details?: Record<string, string>;
+} & Error;
+
+export async function retrieveOrder(accessToken: string, orderID: string) {
```
Comment (gregjopa) [inline src/order/retrieve-order.ts:21]: nit: can we rename this to `getOrder` instead of `retrieveOrder`? That way we match the naming convention of the public v2 orders api.

File: src/order/patch-order.ts [hunk 6]
```diff
@@ -0,0 +1,110 @@
+import { fetch } from "undici";
```
Comment (dtjones404) [inline src/order/patch-order.ts:1]: Looks like `undici.fetch` only works on Node 16.8 or later:

https://www.npmjs.com/package/undici#undicifetchinput-init-promise

Seems like you get an error on earlier versions of Node:

```
callback: 'onError', errorObject: Error: createOrder callback failed - (0 , undici_1.fetch) is not a function
    at http://127.0.0.1…}
```

might be worth adding an `.nvmrc` or calling this out in the Readme

File: src/controller/order-controller.ts [hunk 7]
```diff
@@ -127,3 +162,66 @@ export async function captureOrderController(fastify: FastifyInstance) {
...
+) {
+  const { access_token: accessToken } = await getAuthToken();
+  const { orderID } = request.body as { orderID: string };
+  const data = await getOrder(accessToken, orderID);
+  reply.send(data);
+}
+
+export async function getOrderController(fastify: FastifyInstance) {
+  fastify.route({
+    method: "GET",
```
Comment (dtjones404) [inline src/controller/order-controller.ts:223]: This might need to be a POST, if we're expecting a request body in the handler.

File: src/order/retrieve-order.ts [hunk 8]
```diff
@@ -0,0 +1,68 @@
+import { fetch } from "undici";
```
Comment (dtjones404) [inline src/order/retrieve-order.ts:1]: I like the idea of renaming this file to `get-order.ts`, now that the function has been renamed.

File: src/order/patch-order.ts (hunk 6 above)
Comment (gregjopa) [reply src/order/patch-order.ts:1]: Great point @dtjones404! would you be up for sending a PR to add this? 

If we want to get fancy, we could enforce it with a semver check similar to what we do in checkout-components with this script helper: https://github.com/paypal/paypal-checkout-components/blob/main/scripts/check-node-version.js

File: src/data/shippings.json [hunk 9]
```diff
@@ -0,0 +1,17 @@
+{
```
Comment (gregjopa) [inline src/data/shippings.json:1]: Can we rename this file to shipping-cost.json?

File: src/controller/order-controller.ts [hunk 10]
```diff
@@ -41,11 +46,15 @@ async function createOrderHandler(
       {
         amount: {
           currency_code: "USD",
-          value: totalAmount,
+          value: (totalAmount + 5).toString(),
```
Comment (gregjopa) [inline src/controller/order-controller.ts:49]: Instead of hard-coding 5 here. Let's pull this default value from the new shipping-cost.json file. Ex:
```js
import shippingCost from "../data/shipping-cost.json";

// this can be the way to get the value of 5
Number(shippingCost.DEFAULT)
```

File: src/controller/order-controller.ts (hunk 7 above)
Comment (gregjopa) [reply src/controller/order-controller.ts:200]: I think a GET is fine here to match the backend orders api format.

File: src/order/patch-order.ts [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+import config from "../config";
+import { getOrder } from "./get-order";
+import type { ShippingAddress } from "@paypal/paypal-js";
+import shippings from "../data/shippings.json";
```
Comment (gregjopa) [inline src/order/patch-order.ts:5]:
```suggestion
import shippingCost from "../data/shipping-cost.json";
```

**Review by gregjopa — APPROVED** [review]
Great work @xuanwan05! 💯
